version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password_9921
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://quiz_user:quiz_password_9921@db:5432/quiz_db?schema=public
      - JWT_SECRET=quiz-class-secret-key-12345
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_WS_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data:
